# Default values for datadome-istio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

createDestinationRule: true
createServiceEntry: true

istio:
  portNumber: 8080
  proxyVersion: ^1\.7.*
  workloadSelector:
    labels:
      datadome: 'enabled'
datadome:
  api_key: TOP_SECRET_API_KEY
  api_url: api.datadome.co
  api_timeout: 200 # in milliseconds
  api_connection_timeout: "100ms" # go time format
  url_patterns:
  - '^www.blablacar.'
  - '^edge.blablacar.com'
  - '^http%-echo.staging%-1.blbl.cr'
  uri_patterns:
