# Default values for datadome-istio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

destinationRule:
  enabled: true

serviceEntry:
  enabled: true

istio:
  portNumber: 8080
  workloadSelector:
    labels:
      datadome: "enabled"

datadome:
  api_key: TOP_SECRET_API_KEY
  api_url: api.datadome.co
  api_timeout: 200 # in milliseconds
  api_connection_timeout: "100ms" # go time format
