{{- if .Values.destinationRule.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}
  namespace: istio-system
  {{- if .Values.istio.resourceValidation.enabled }}
  labels:
    istio.io/tag: stable
  {{- end }}
spec:
  host: {{ .Values.datadome.api_url }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        connectTimeout: {{ .Values.datadome.api_connection_timeout }}
      http:
        maxRetries: 1
    portLevelSettings:
    - port:
        number: 443
      tls:
          mode: SIMPLE # initiates HTTPS when accessing api.datadome.co
{{- end }}
