---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ .Release.Name }}
  namespace: istio-system
  {{- if .Values.istio.resourceValidation.enabled }}
  labels:
      istio.io/tag: stable
  {{- end }}
spec:
  workloadSelector:
    labels:
      {{- range $key, $val := .Values.istio.workloadSelector.labels }}
      {{ $key }}: {{ $val }}
      {{- end }}
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: {{ .Values.istio.portNumber }}
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
      {{- if .Values.istio.proxyVersion }}
      proxy:
        proxyVersion: {{ .Values.istio.proxyVersion }}
      {{- end }}
    patch:
      operation: INSERT_BEFORE
      value:
        name: {{ .Release.Name }}.lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            local options = {
              API_KEY = '{{ .Values.datadome.api_key }}',
              API_TIMEOUT = {{ .Values.datadome.api_timeout}},
              DATADOME_CLUSTER_NAME = 'outbound|443||{{ .Values.datadome.api_url }}',
              DATADOME_ENDPOINT = '{{ .Values.datadome.api_url }}',
              DATADOME_TENANT_NAME = '{{ .Release.Name }}',
              ENABLE_UNPROTECTED_CACHED_RESPONSE = true,
              {{- if .Values.datadome.uri_patterns -}}
              URI_PATTERNS = {
                {{ range .Values.datadome.uri_patterns }}
                  {{- . | quote -}},
                {{ end -}}
              },
              {{ end }}
              {{- if .Values.datadome.uri_patterns_exclusion -}}
              URI_PATTERNS_EXCLUSION = {
                {{ range .Values.datadome.uri_patterns_exclusion }}
                  {{- . | quote -}},
                {{ end -}}
              }
              {{ end }}
            }
            {{- tpl (.Files.Get "files/datadome.lua") . | nindent 12 }}
