---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: datadome-api
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      {{- range $key, $val := .Values.istio.workloadSelector.labels }}
      {{ $key }}: {{ $val }}
      {{- end }}
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 80
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.lua
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.http.lua.v3.Lua
          inlineCode: |
            local options = {
              API_TIMEOUT = {{ .Values.datadome.api_timeout}},
              API_KEY = '{{ .Values.datadome.api_key }}',
              URL_PATTERNS = {
                {{ range .Values.datadome.url_patterns }}
                  {{- . | quote -}},
                {{ end -}}
              },
              {{- if .Values.datadome.uri_patterns -}}
              URI_PATTERNS = {
                {{ range .Values.datadome.uri_patterns }}
                  {{- . | quote -}},
                {{ end -}}
              },
              {{ end }}
              {{- if .Values.datadome.uri_patterns_exclusion -}}
              URI_PATTERNS_EXCLUSION = {
                {{ range .Values.datadome.uri_patterns_exclusion }}
                  {{- . | quote -}},
                {{ end -}}
              }
              {{ end }}
            }
            {{- tpl (.Files.Get "files/datadome.lua") . | nindent 12 }}
