{{- if .Values.serviceEntry.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}
  namespace: istio-system
  {{- if .Values.istio.resourceValidation.enabled }}
  labels:
      istio.io/tag: stable
  {{- end }}
spec:
  hosts:
  - {{ .Values.datadome.api_url }}
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
{{- end }}
