---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: datadome-api
  namespace: istio-system
spec:
  hosts:
  - {{ .Values.datadome.api_url }}
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: DNS
